"""CLI entry point: generate Milestone 1's Auth-cluster Jira + Xray CSVs.

Wires Tasks 1.1-1.5 together (squads -> cluster injection -> features ->
test logs -> CSV) and writes Task 1.6's validation report. Deterministic:
same --seed produces byte-identical output (PROJECT.md Success Criteria #6).

    python3 -m blocker_generator
    python3 -m blocker_generator --seed 7 --output-dir /tmp/out
"""
from __future__ import annotations

import argparse
from pathlib import Path

from blocker_generator.clusters import CLUSTER_1_AUTH
from blocker_generator.csv_io import write_jira_csv, write_test_logs_csv
from blocker_generator.features import generate_dataset
from blocker_generator.squads import build_auth_subgraph
from blocker_generator.sprints import week_for_date
from blocker_generator.xray_logs import generate_test_logs
import random


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate the Milestone 1 Auth-cluster Jira + Xray CSVs."
    )
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--output-dir", default="data")
    p.add_argument("--report-dir", default="docs")
    return p


def write_validation_report(dataset, test_logs, path: Path, seed: int) -> None:
    features = [r for r in dataset if r.type == "Story"]
    blockers = [r for r in dataset if r.type == "Sub-task"]
    week3_features = [r for r in features if week_for_date(r.created.date()) == 3]
    window_density = (len(blockers) / len(week3_features) * 100) if week3_features else 0.0
    global_density = (len(blockers) / len(features) * 100) if features else 0.0
    flaky = [r for r in test_logs if r.flaky]

    resolved_cycle_times = [r.cycle_time_days for r in blockers if r.cycle_time_days is not None]
    still_waiting = [r for r in dataset if r.status == "Waiting"]
    in_progress = [r for r in features if r.status == "In Progress"]

    lines = [
        "# Milestone 1 Dataset Summary",
        "",
        "Generated by `python3 -m blocker_generator` — regenerate anytime with the "
        "same `--seed` for identical output. See specification/ARCHITECTURE.md for "
        "the domain model and BACKLOG.md Task 1.4 for the corrected acceptance criteria.",
        "",
        "## Dataset size",
        "",
        f"- Total rows: {len(dataset)} ({len(features)} features + {len(blockers)} blockers)",
        f"- Test log rows: {len(test_logs)}",
        "",
        "## Blocker density (window-scoped per PM ruling, not global)",
        "",
        f"- Window-scoped (week 3 only): {window_density:.1f}%",
        f"- Global (all 12 sprints): {global_density:.2f}%",
        "",
        "## Cluster signature",
        "",
        "- Auth cluster (Cluster-1-Auth): week 3, cascades to Checkout/Payments with 1-day lag",
        f"- Peak resolved waiting cycle time: {max(resolved_cycle_times, default=0):.0f} day(s)",
        "",
        "## Live status distribution (PBI 2.1, 2026-08-24)",
        "",
        f"- Currently Waiting (blocker rows not yet cleared): {len(still_waiting)}",
        f"- In Progress (feature rows, aging candidates — dashboard computes age as NOW()-Created): {len(in_progress)} ({len(in_progress) / len(features) * 100:.1f}% of features)",
        f"- Done (resolved, historical): {len(dataset) - len(still_waiting) - len(in_progress)}",
        "",
        "## Test coverage",
        "",
        f"- Flaky test rows: {len(flaky)} / {len(test_logs)}",
        "",
        "## Generation parameters",
        "",
        f"- `seed`: {seed}",
        "",
    ]
    path.write_text("\n".join(lines))


def main(argv=None) -> int:
    args = build_arg_parser().parse_args(argv)

    squads = build_auth_subgraph()
    dataset = generate_dataset(args.seed, squads, [CLUSTER_1_AUTH])
    test_logs = generate_test_logs(random.Random(args.seed), dataset)

    output_dir = Path(args.output_dir)
    report_dir = Path(args.report_dir)
    write_jira_csv(dataset, output_dir / "v1_auth_cluster_high_density.csv")
    write_test_logs_csv(test_logs, output_dir / "v1_auth_cluster_test_logs.csv")
    write_validation_report(dataset, test_logs, report_dir / "VALIDATION_REPORT_Milestone_1.md", args.seed)

    features = [r for r in dataset if r.type == "Story"]
    blockers = [r for r in dataset if r.type == "Sub-task"]
    print(f"Generated {len(features)} features, {len(blockers)} blockers, {len(test_logs)} test log rows.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
